# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/scripts/UI/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("600x720")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=720,
    width=600,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    300.0,
    360.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=210.0,
    y=623.0,
    width=180.1081085205078,
    height=56.0
)

canvas.create_text(
    40.0,
    300.0,
    anchor="nw",
    text="Blacklist: ",
    fill="#FFFFFF",
    font=("Arial", 24 * -1)
)

canvas.create_text(
    40.0,
    40.0,
    anchor="nw",
    text="Tags: ",
    fill="#FFFFFF",
    font=("Arial", 24 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    355.0,
    160.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#19457A",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Arial", 24)
)
entry_1.place(
    x=150.0,
    y=40.0,
    width=410.0,
    height=238.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    355.0,
    360.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#19457A",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Arial", 24)
)
entry_2.place(
    x=150.0,
    y=300.0,
    width=410.0,
    height=118.0
)

canvas.create_text(
    39.0,
    440.0,
    anchor="nw",
    text="Output directory: ",
    fill="#FFFFFF",
    font=("Arial", 24 * -1)
)

canvas.create_text(
    39.0,
    526.0,
    anchor="nw",
    text="Count: ",
    fill="#FFFFFF",
    font=("Arial", 24 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=53.0,
    y=478.0,
    width=29.0,
    height=29.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    324.5,
    492.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#19457A",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Arial", 24)
)
entry_3.place(
    x=89.0,
    y=478.0,
    width=471.0,
    height=26.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    174.5,
    541.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#19457A",
    fg="#FFFFFF",
    highlightthickness=0,
    font=("Arial", 24)
)
entry_4.place(
    x=127.0,
    y=527.0,
    width=95.0,
    height=26.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=34.0,
    y=566.0,
    width=213.0,
    height=48.0
)
window.resizable(False, False)
window.mainloop()
